services:
  web:
    container_name: erp_framework_web_dev
    build: .
    env_file:
      - .env
    environment:
      # Point DB_HOST to the external MySQL container's name
      DB_HOST: mysql
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq
    networks:
      - shared-network
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared-network
    restart: always

  celery:
    container_name: erp_framework_celery_dev
    build: .
    command: celery -A erp_framework worker -l info
    env_file:
      - .env
    environment:
      # Point DB_HOST to the external MySQL container's name
      DB_HOST: mysql
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq
    networks:
      - shared-network
    restart: always

networks:
  shared-network:
    external: true

