# Generated by Django 5.2.17 on 2026-08-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalemail',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='internalemail',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='internalemailattachment',
            name='email',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='InternalEmail',
        ),
        migrations.DeleteModel(
            name='InternalEmailAttachment',
        ),
    ]
