# Generated by Django 6.0.6 on 2026-07-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g., REQUIRE_PO_APPROVAL', max_length=100, unique=True)),
                ('value', models.JSONField(help_text='Store values as JSON (e.g., true, 100, "string")')),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Configurations',
            },
        ),
    ]
