# Generated by Django 5.2.16 on 2026-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization/Company Name')),
                ('owner_name', models.CharField(max_length=150, verbose_name='Owner Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Contact/Phone Number')),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN Number')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='License Number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/', verbose_name='Organization Logo')),
            ],
            options={
                'verbose_name': 'Organization Details',
                'verbose_name_plural': 'Organization Details',
            },
        ),
    ]
