# Generated by Django 5.2.16 on 2026-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicalattachment_historicalsavedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalroute',
            name='required_permission',
            field=models.CharField(blank=True, help_text="e.g., 'inventory.approve_purchaseorder'", max_length=255),
        ),
    ]
