# Generated by Django 5.2.16 on 2026-07-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_internalemail_internalemailattachment'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymenttransaction')),
            ],
        ),
    ]
