# Generated by Django 5.2.16 on 2026-07-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoicepaymentallocation'),
        ('purchasing', '0002_historicalsupplierbill_supplierbill_and_more'),
        ('sales', '0004_b2bsalesinvoice_b2bsalesinvoiceline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepaymentallocation',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.b2bsalesinvoice'),
        ),
        migrations.AddField(
            model_name='invoicepaymentallocation',
            name='supplier_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchasing.supplierbill'),
        ),
    ]
