import uuid
import hashlib
import jwt
from django.conf import settings
from .config import Config

class LicenseManager:
    # The PUBLIC KEY verifies the JWT token generated by the vendor's PRIVATE KEY.
    PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlwcYAz4oX/VB5aVbi9bQ
EF/04frvteiRUSTUfoj4TocLRh9bQQQDEfsAXb5KGwfAyaeB9qcTE0+tPOIk1Z5T
wYtjUFvFuV0pWs7ymk+tPSlY6rWh6wl+6DcZGudlyQ7pxnIe+LF9UgBXD6b2hpyD
C0r27eYJfn+bBefbPxz8hlBE4sQ3H0IU1ZBNbp29Tdvoj825ltvqODvLJjyv2CYD
c9ullLEABEKvJKZ0PWRrgryTE/4vD94AdWu7dDyoifOQ/Q2OY84wQk2bczXT4pGi
82tRJbXGr4u7RFt2dNtuqxdfwz43zMeXSpi6MOPEEYIIfpuhliM7eKYc6erX3xpb
QwIDAQAB
-----END PUBLIC KEY-----"""

    @staticmethod
    def get_hardware_id():
        """Generates a highly secure Hardware ID unique to this machine and installation."""
        mac = uuid.getnode()
        # Bind strictly to this system using mac + unique django secret
        raw_id = f"{mac}_{settings.SECRET_KEY[:10]}"
        return hashlib.sha256(raw_id.encode('utf-8')).hexdigest()[:20]

    @staticmethod
    def verify_license(license_key):
        """Verifies the JWT payload against the Public Key, Hardware ID, and Expiration."""
        if not license_key:
            return False, "No license installed."
            
        try:
            # PyJWT automatically verifies the 'exp' (expiration) claim if present!
            payload = jwt.decode(license_key, LicenseManager.PUBLIC_KEY, algorithms=["RS256"])
            
            # Verify Hardware ID binding to prevent copying licenses to other servers
            if payload.get('hwid') != LicenseManager.get_hardware_id():
                return False, "License is bound to a different machine (Hardware ID mismatch)."
                
            return True, payload
            
        except jwt.ExpiredSignatureError:
            return False, "License has expired. Please renew."
        except jwt.InvalidTokenError:
            return False, "License key is invalid or corrupted."

    @staticmethod
    def get_current_license():
        """Fetches the license key string from the dynamic configuration store."""
        return Config.get('APP_LICENSE_KEY')
