import uuid
import hashlib
import jwt
from django.conf import settings
from .config import Config

class LicenseManager:
    # The PUBLIC KEY verifies the JWT token generated by the vendor's PRIVATE KEY.
    PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKkGJ8b03yrpYwDv1Zba
auywP+3k6C6ZHlqrKXR1adh7AJlwKZQ3tMKYQw/FlJ7qYtzw9h8t2jBCRtjANsJ2
+pIW8tZ8z19ACsnGIIZow9tSE2tzgCg/+r2DXXU11DahvZ4UXwj5at2WYJkHfVwk
7QjpvHQUfM7pwh4TexgW98twNfn0/lEXCUu+ihM0LaTjKh+GJXhOZyFsnzSzxuPU
87agXBFj42TtDwhfM4WhpHNl3xjnul+cul+84AdN6hp+aEaoPhzsg2wXqgqEz8Vq
zq1t2LlDN5h8ZLwL52UYswv6XizzyXCGHkbJSklk2Eel41hFPC9IcgHgPb+7VL5r
qwIDAQAB
-----END PUBLIC KEY-----"""

    @staticmethod
    def get_hardware_id():
        """Generates a highly secure Hardware ID unique to this machine and installation."""
        mac = uuid.getnode()
        # Bind strictly to this system using mac + unique django secret
        raw_id = f"{mac}_{settings.SECRET_KEY[:10]}"
        return hashlib.sha256(raw_id.encode('utf-8')).hexdigest()[:20]

    @staticmethod
    def verify_license(license_key):
        """Verifies the JWT payload against the Public Key, Hardware ID, and Expiration."""
        if not license_key:
            return False, "No license installed."
            
        try:
            # PyJWT automatically verifies the 'exp' (expiration) claim if present!
            payload = jwt.decode(license_key, LicenseManager.PUBLIC_KEY, algorithms=["RS256"])
            
            # Verify Hardware ID binding to prevent copying licenses to other servers
            if payload.get('hwid') != LicenseManager.get_hardware_id():
                return False, "License is bound to a different machine (Hardware ID mismatch)."
                
            return True, payload
            
        except jwt.ExpiredSignatureError:
            return False, "License has expired. Please renew."
        except jwt.InvalidTokenError:
            return False, "License key is invalid or corrupted."

    @staticmethod
    def get_current_license():
        """Fetches the license key string from the dynamic configuration store."""
        return Config.get('APP_LICENSE_KEY')
