import datetime
from decimal import Decimal
from django.test import TestCase
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils import timezone

from core.models import Organization, Workflow, State
from .models import (
    IndustryPreset, BusinessProfile, ResourceType, Resource,
    OperatingSchedule, Holiday, SlotOverride, Customer,
    Booking, BookingItem, Addon, PricingRule, TaxRule
)
from .services.slot_engine import SlotEngine
from .services.pricing_engine import PricingEngine
from .services.booking_service import BookingService

User = get_user_model()


class BookingSystemTests(TestCase):
    """
    Comprehensive test suite verifying the Generic Booking Management System.
    """

    def setUp(self) -> None:
        # Create user
        self.user = User.objects.create_user(username='testuser', email='test@example.com', password='password123')

        # Create Organization
        self.organization = Organization.objects.create(
            name="Alpha Corp",
            owner_name="Jane Doe",
            email="jane@alpha.com",
            phone="1234567890"
        )

        # Retrieve seeded IndustryPresets (created by migrations)
        self.hotel_preset = IndustryPreset.objects.get(slug="hotel-resort")
        self.opd_preset = IndustryPreset.objects.get(slug="hospital-opd")

        # Setup Business Profiles
        self.hotel_business = BusinessProfile.objects.create(
            organization=self.organization,
            industry=self.hotel_preset,
            name="Grand Hotel Resort",
            timezone="UTC",
            currency="USD",
            config_overrides={"max_advance_days": 180}
        )

        self.opd_business = BusinessProfile.objects.create(
            organization=self.organization,
            industry=self.opd_preset,
            name="General Hospital OPD",
            timezone="UTC",
            currency="USD"
        )

        # Setup Core Workflow states (simulating erp_framework Workflow Engine)
        self.booking_workflow = Workflow.objects.create(
            name="Booking Workflow",
            model_name="bookings.Booking"
        )
        self.draft_state = State.objects.create(workflow=self.booking_workflow, name="Draft", is_initial=True)
        self.pending_state = State.objects.create(workflow=self.booking_workflow, name="Pending")
        self.confirmed_state = State.objects.create(workflow=self.booking_workflow, name="Confirmed")
        self.completed_state = State.objects.create(workflow=self.booking_workflow, name="Completed")
        self.cancelled_state = State.objects.create(workflow=self.booking_workflow, name="Cancelled", is_final=True)

        # Resource Types
        self.room_type = ResourceType.objects.create(
            business=self.hotel_business,
            name="Deluxe Room",
            default_capacity=2,
            default_duration_minutes=None
        )

        self.doctor_type = ResourceType.objects.create(
            business=self.opd_business,
            name="Cardiologist",
            default_capacity=1,
            default_duration_minutes=15
        )

        # Resources
        self.room_101 = Resource.objects.create(
            business=self.hotel_business,
            resource_type=self.room_type,
            name="Room 101",
            code="R101",
            capacity=2
        )

        self.doctor_smith = Resource.objects.create(
            business=self.opd_business,
            resource_type=self.doctor_type,
            name="Dr. Smith",
            code="DOC-SMITH",
            capacity=1
        )

        # Create Customer
        self.customer = Customer.objects.create(
            business=self.hotel_business,
            name="John Smith",
            email="john@smith.com",
            phone="9876543210"
        )

    def test_seeded_presets_exist(self) -> None:
        """Verify that the 26 industry presets were seeded by migrations."""
        presets_count = IndustryPreset.objects.count()
        self.assertGreaterEqual(presets_count, 26)

    def test_config_inheritance(self) -> None:
        """Verify BusinessProfile retrieves configuration correctly from defaults and overrides."""
        # Config value overridden in business setup
        self.assertEqual(self.hotel_business.get_config("max_advance_days"), 180)
        # Config value inherited from IndustryPreset
        self.assertEqual(self.hotel_business.get_config("cancellation_hours"), 24)
        # Check defaults fallback
        self.assertEqual(self.hotel_business.get_config("non_existent_key", "default_val"), "default_val")

    def test_slot_engine_weekly_schedule_slots(self) -> None:
        """Verify availability slots generated by OperatingSchedule."""
        # Create general business schedule for doctor_smith's profile (e.g. Wednesday 09:00 to 11:00, 30 min slots)
        OperatingSchedule.objects.create(
            business=self.opd_business,
            resource=self.doctor_smith,
            day_of_week=2,  # Wednesday
            start_time=datetime.time(9, 0),
            end_time=datetime.time(11, 0),
            slot_duration_minutes=30,
            max_concurrent=1
        )

        # Target date is a Wednesday
        target_date = datetime.date(2026, 7, 22)
        slots = SlotEngine.get_available_slots(self.opd_business, self.doctor_smith, target_date)
        
        # Expected slots: 09:00-09:30, 09:30-10:00, 10:00-10:30, 10:30-11:00 (4 slots)
        self.assertEqual(len(slots), 4)
        self.assertEqual(slots[0]["start_time"], datetime.time(9, 0))
        self.assertEqual(slots[0]["capacity_remaining"], 1)

    def test_slot_engine_holiday_and_block_overrides(self) -> None:
        """Verify that Holidays and Block overrides remove slot availability."""
        OperatingSchedule.objects.create(
            business=self.opd_business,
            resource=self.doctor_smith,
            day_of_week=2,
            start_time=datetime.time(9, 0),
            end_time=datetime.time(11, 0),
            slot_duration_minutes=30
        )
        target_date = datetime.date(2026, 7, 22)

        # 1. Add Holiday
        Holiday.objects.create(business=self.opd_business, date=target_date, reason="Medical Conference")
        slots = SlotEngine.get_available_slots(self.opd_business, self.doctor_smith, target_date)
        self.assertEqual(len(slots), 0)

        # Remove Holiday, add BLOCK override
        Holiday.objects.all().delete()
        SlotOverride.objects.create(
            business=self.opd_business,
            resource=self.doctor_smith,
            date=target_date,
            override_type='BLOCK'
        )
        slots = SlotEngine.get_available_slots(self.opd_business, self.doctor_smith, target_date)
        self.assertEqual(len(slots), 0)

    def test_pricing_engine_hourly_rule(self) -> None:
        """Verify dynamic calculations for hourly pricing model."""
        # Create pricing rule for Deluxe Room (hourly model)
        PricingRule.objects.create(
            business=self.hotel_business,
            resource_type=self.room_type,
            pricing_model='HOURLY',
            base_price=Decimal('25.00'),
            valid_from=datetime.date(2026, 1, 1)
        )

        start_dt = timezone.make_aware(datetime.datetime(2026, 7, 20, 10, 0))
        end_dt = timezone.make_aware(datetime.datetime(2026, 7, 20, 12, 30))  # 2.5 hours -> rounded up to 3 hours

        pricing = PricingEngine.calculate_price(
            business=self.hotel_business,
            resource=self.room_101,
            start_dt=start_dt,
            end_dt=end_dt,
            quantity=1
        )

        # 3 hours * 25 = 75
        self.assertEqual(pricing["total_amount"], Decimal('75.00'))
        self.assertEqual(pricing["duration_units"], 3.0)

    def test_pricing_engine_multipliers_and_taxes(self) -> None:
        """Verify peak/weekend multipliers and tax inclusive/exclusive calculations."""
        PricingRule.objects.create(
            business=self.hotel_business,
            resource_type=self.room_type,
            pricing_model='FLAT',
            base_price=Decimal('100.00'),
            peak_multiplier=Decimal('1.50'),
            weekend_multiplier=Decimal('1.20'),
            valid_from=datetime.date(2026, 1, 1)
        )

        # Exclusive Tax Rule
        TaxRule.objects.create(
            business=self.hotel_business,
            name="Vat 10%",
            rate=Decimal('10.00'),
            is_inclusive=False
        )

        # Saturday booking (weekend)
        start_dt = timezone.make_aware(datetime.datetime(2026, 7, 25, 12, 0))  # Saturday
        end_dt = timezone.make_aware(datetime.datetime(2026, 7, 25, 14, 0))

        pricing = PricingEngine.calculate_price(
            business=self.hotel_business,
            resource=self.room_101,
            start_dt=start_dt,
            end_dt=end_dt,
            quantity=1
        )

        # Base: 100 * 1.50 (peak) * 1.20 (weekend) = 180.00
        # Tax: 180 * 0.10 = 18.00
        # Total: 198.00
        self.assertEqual(pricing["subtotal"], Decimal('180.00'))
        self.assertEqual(pricing["tax_amount"], Decimal('18.00'))
        self.assertEqual(pricing["total_amount"], Decimal('198.00'))

    def test_booking_creation_service(self) -> None:
        """Verify successful create booking transaction with state machine assignment."""
        # Operating schedule Wednesday
        OperatingSchedule.objects.create(
            business=self.hotel_business,
            resource=self.room_101,
            day_of_week=2,
            start_time=datetime.time(0, 0),
            end_time=datetime.time(23, 59),
            slot_duration_minutes=None
        )

        # Pricing Rule
        PricingRule.objects.create(
            business=self.hotel_business,
            resource_type=self.room_type,
            pricing_model='DAILY',
            base_price=Decimal('150.00'),
            valid_from=datetime.date(2026, 1, 1)
        )

        # Addon
        spa_addon = Addon.objects.create(
            business=self.hotel_business,
            name="Spa Treatment",
            price=Decimal('50.00')
        )

        # Dynamic slot parameters (Wednesday)
        start_dt = timezone.make_aware(datetime.datetime(2026, 7, 22, 14, 0))
        end_dt = timezone.make_aware(datetime.datetime(2026, 7, 23, 14, 0)) # 1 Day

        # Register workflow state relation mock
        self.room_101.resource_type.business.config_overrides = {"requires_approval": False}
        self.room_101.resource_type.business.save()

        booking = BookingService.create_booking(
            business=self.hotel_business,
            customer=self.customer,
            start_dt=start_dt,
            end_dt=end_dt,
            items=[{"resource": self.room_101, "quantity": 1}],
            addons=[{"addon": spa_addon, "quantity": 1}],
            slot_mode='date_range'
        )

        self.assertIsNotNone(booking.booking_number)
        # Daily duration = 1 day * 150 = 150. Addon: 50. Total subtotal: 200
        self.assertEqual(booking.subtotal, Decimal('200.00'))
        self.assertEqual(booking.total_amount, Decimal('200.00'))
        self.assertEqual(booking.status, 'Confirmed') # auto confirmed based on configuration override
        self.assertEqual(booking.items.count(), 1)
        self.assertEqual(booking.addons.count(), 1)

    def test_booking_collision_raises_validation_error(self) -> None:
        """Verify capacity constraints prevent double booking collisions."""
        OperatingSchedule.objects.create(
            business=self.hotel_business,
            resource=self.room_101,
            day_of_week=2,
            start_time=datetime.time(12, 0),
            end_time=datetime.time(14, 0),
            slot_duration_minutes=None
        )

        start_dt = timezone.make_aware(datetime.datetime(2026, 7, 22, 12, 0))
        end_dt = timezone.make_aware(datetime.datetime(2026, 7, 22, 14, 0))

        # First booking takes full capacity (Room 101 capacity is 2, first books 2)
        BookingService.create_booking(
            business=self.hotel_business,
            customer=self.customer,
            start_dt=start_dt,
            end_dt=end_dt,
            items=[{"resource": self.room_101, "quantity": 2}],
            slot_mode='time_slot'
        )

        # Second booking should fail due to collision
        with self.assertRaises(ValidationError):
            BookingService.create_booking(
                business=self.hotel_business,
                customer=self.customer,
                start_dt=start_dt,
                end_dt=end_dt,
                items=[{"resource": self.room_101, "quantity": 1}],
                slot_mode='time_slot'
            )

    def test_cancel_and_reschedule_service(self) -> None:
        """Verify cancellation state changes and rescheduling slot check validations."""
        OperatingSchedule.objects.create(
            business=self.hotel_business,
            resource=self.room_101,
            day_of_week=2,  # Wednesday
            start_time=datetime.time(12, 0),
            end_time=datetime.time(14, 0),
            slot_duration_minutes=None
        )
        OperatingSchedule.objects.create(
            business=self.hotel_business,
            resource=self.room_101,
            day_of_week=3,  # Thursday
            start_time=datetime.time(12, 0),
            end_time=datetime.time(14, 0),
            slot_duration_minutes=None
        )

        start_dt = timezone.make_aware(datetime.datetime(2026, 7, 22, 12, 0))
        end_dt = timezone.make_aware(datetime.datetime(2026, 7, 22, 14, 0))

        booking = BookingService.create_booking(
            business=self.hotel_business,
            customer=self.customer,
            start_dt=start_dt,
            end_dt=end_dt,
            items=[{"resource": self.room_101, "quantity": 1}],
            slot_mode='time_slot'
        )
        self.assertEqual(booking.status, 'Confirmed')

        # Cancel Booking
        cancelled_bk = BookingService.cancel_booking(booking)
        self.assertEqual(cancelled_bk.status, 'Cancelled')

        # Reschedule a booking
        booking2 = BookingService.create_booking(
            business=self.hotel_business,
            customer=self.customer,
            start_dt=start_dt,
            end_dt=end_dt,
            items=[{"resource": self.room_101, "quantity": 1}],
            slot_mode='time_slot'
        )
        
        new_start_dt = timezone.make_aware(datetime.datetime(2026, 7, 23, 12, 0)) # Thursday
        new_end_dt = timezone.make_aware(datetime.datetime(2026, 7, 23, 14, 0))
        
        rescheduled_bk = BookingService.reschedule_booking(booking2, new_start_dt, new_end_dt)
        self.assertEqual(rescheduled_bk.start_datetime, new_start_dt)
