# Generated by Django 6.0.6 on 2026-07-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
        ('inventory', '0003_vendor_remove_purchaseorder_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='workflow_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_instances', to='core.state'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='workflow_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_instances', to='core.state'),
        ),
    ]
