# Generated by Django 5.2.16 on 2026-07-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_barcode_inventoryitem_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
