# Generated by Django 5.2.16 on 2026-07-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='has_expiry_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polineitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polineitem',
            name='received_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polineitem',
            name='received_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
