# Generated by Django 5.2.16 on 2026-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_has_expiry_date_polineitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplied_items',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='inventory.inventoryitem'),
        ),
    ]
