# Generated by Django 5.2.16 on 2026-07-12 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplier_supplied_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplied_items',
        ),
        migrations.CreateModel(
            name='SupplierCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='inventory.inventoryitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to='inventory.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'item')},
            },
        ),
    ]
