# Generated by Django 5.2.16 on 2026-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_supplier_supplied_items_suppliercatalogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplied_items',
            field=models.ManyToManyField(blank=True, related_name='suppliers', through='inventory.SupplierCatalogItem', to='inventory.inventoryitem'),
        ),
    ]
