# Generated by Django 5.2.16 on 2026-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_supplier_supplied_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
