# Generated by Django 5.2.16 on 2026-07-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
