# Generated by Django 5.2.16 on 2026-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_savedreport'),
        ('inventory', '0013_inventoryitem_is_active_supplier_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_9e3971_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['stock_level'], name='inventory_i_stock_l_1e7007_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['unit_price'], name='inventory_i_unit_pr_ebe4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitempricelog',
            index=models.Index(fields=['item', '-changed_at'], name='inventory_i_item_id_c3fc04_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitempricelog',
            index=models.Index(fields=['changed_at'], name='inventory_i_changed_b84bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='polineitem',
            index=models.Index(fields=['expiry_date'], name='inventory_p_expiry__288b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='inventory_p_created_36002a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='inventory_s_is_acti_3743da_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercatalogitem',
            index=models.Index(fields=['price'], name='inventory_s_price_0a7c2a_idx'),
        ),
    ]
