# Generated by Django 5.2.16 on 2026-07-14 08:25

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_historicalinventoryitem_historicalpolineitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='status',
            field=django_fsm.FSMField(default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=django_fsm.FSMField(default='Draft', max_length=50),
        ),
    ]
