# Generated by Django 5.2.16 on 2026-07-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_historicalpurchaseorder_status_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': (('approve_purchaseorder', 'Can approve purchase order'),)},
        ),
    ]
