# Generated by Django 5.2.16 on 2026-07-18 06:50

import django.db.models.deletion
import django_fsm
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_internalemail_internalemailattachment'),
        ('crm', '0001_initial'),
        ('fleet_mgmt', '0001_initial'),
        ('hrms', '0004_historicalperformanceappraisal_performanceappraisal_and_more'),
        ('logistics_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='Draft', max_length=50)),
                ('manifest_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_manifests', to='hrms.employee')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics_core.route')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_manifests', to='fleet_mgmt.vehicle')),
                ('workflow_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_instances', to='core.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDispatchManifest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='Draft', max_length=50)),
                ('manifest_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrms.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics_core.route')),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet_mgmt.vehicle')),
                ('workflow_state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.state')),
            ],
            options={
                'verbose_name': 'historical dispatch manifest',
                'verbose_name_plural': 'historical dispatch manifests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWaybill',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='Draft', max_length=50)),
                ('waybill_number', models.CharField(db_index=True, max_length=50)),
                ('sender_address', models.TextField(blank=True)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_address', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('chargeable_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('destination_zone', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics_core.zone')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origin_zone', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics_core.zone')),
                ('sender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.customer')),
                ('service_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics_core.servicetype')),
                ('workflow_state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.state')),
            ],
            options={
                'verbose_name': 'historical waybill',
                'verbose_name_plural': 'historical waybills',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='Draft', max_length=50)),
                ('waybill_number', models.CharField(max_length=50, unique=True)),
                ('sender_address', models.TextField(blank=True)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_address', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('chargeable_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('destination_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_waybills', to='logistics_core.zone')),
                ('origin_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_waybills', to='logistics_core.zone')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_waybills', to='crm.customer')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics_core.servicetype')),
                ('workflow_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_instances', to='core.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_by', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='pods/signatures/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pods/photos/')),
                ('notes', models.TextField(blank=True)),
                ('waybill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='courier.waybill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProofOfDelivery',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('received_by', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('signature', models.TextField(blank=True, max_length=100, null=True)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('waybill', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courier.waybill')),
            ],
            options={
                'verbose_name': 'historical proof of delivery',
                'verbose_name_plural': 'historical proof of deliverys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalManifestItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, help_text='Delivery order sequence')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manifest', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courier.dispatchmanifest')),
                ('waybill', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courier.waybill')),
            ],
            options={
                'verbose_name': 'historical manifest item',
                'verbose_name_plural': 'historical manifest items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ManifestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, help_text='Delivery order sequence')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courier.dispatchmanifest')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_items', to='courier.waybill')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('manifest', 'waybill')},
            },
        ),
    ]
