# Generated by Django 5.2.16 on 2026-07-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_historicalpaymenttransaction_historicalwaitlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='booking',
        ),
        migrations.DeleteModel(
            name='HistoricalPaymentTransaction',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
